# Generated by Django 5.0.4 on 2024-05-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['user_number'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Члены команды'},
        ),
        migrations.AddField(
            model_name='team',
            name='user_number',
            field=models.IntegerField(default=0),
        ),
    ]
