# Generated by Django 5.0.4 on 2024-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_alter_team_options_team_user_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_number'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(default=0),
        ),
    ]
