# Generated by Django 5.0.4 on 2024-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_alter_project_options_project_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_ru',
        ),
    ]
