# Generated by Django 5.0.4 on 2024-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_projectad_remove_project_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_diving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('about_title', models.TextField(verbose_name='О проекте(заголовок)')),
                ('about_title_ru', models.TextField(null=True, verbose_name='О проекте(заголовок)')),
                ('about_title_en', models.TextField(null=True, verbose_name='О проекте(заголовок)')),
                ('about_1', models.TextField(verbose_name='О проекте(абз. 1)')),
                ('about_1_ru', models.TextField(null=True, verbose_name='О проекте(абз. 1)')),
                ('about_1_en', models.TextField(null=True, verbose_name='О проекте(абз. 1)')),
                ('about_2', models.TextField(verbose_name='О проекте(абз. 2)')),
                ('about_2_ru', models.TextField(null=True, verbose_name='О проекте(абз. 2)')),
                ('about_2_en', models.TextField(null=True, verbose_name='О проекте(абз. 2)')),
                ('about_3', models.TextField(verbose_name='О проекте(абз. 3)')),
                ('about_3_ru', models.TextField(null=True, verbose_name='О проекте(абз. 3)')),
                ('about_3_en', models.TextField(null=True, verbose_name='О проекте(абз. 3)')),
                ('details_title', models.TextField(verbose_name='Детали(заголовок)')),
                ('details_title_ru', models.TextField(null=True, verbose_name='Детали(заголовок)')),
                ('details_title_en', models.TextField(null=True, verbose_name='Детали(заголовок)')),
                ('details_1', models.TextField(verbose_name='Детали(абз. 1)')),
                ('details_1_ru', models.TextField(null=True, verbose_name='Детали(абз. 1)')),
                ('details_1_en', models.TextField(null=True, verbose_name='Детали(абз. 1)')),
                ('details_2', models.TextField(verbose_name='Детали(абз. 2)')),
                ('details_2_ru', models.TextField(null=True, verbose_name='Детали(абз. 2)')),
                ('details_2_en', models.TextField(null=True, verbose_name='Детали(абз. 2)')),
                ('details_3', models.TextField(verbose_name='Детали(абз. 3)')),
                ('details_3_ru', models.TextField(null=True, verbose_name='Детали(абз. 3)')),
                ('details_3_en', models.TextField(null=True, verbose_name='Детали(абз. 3)')),
            ],
            options={
                'verbose_name': 'Арт-дивинг',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectAD',
        ),
    ]
