# Generated by Django 5.0.4 on 2024-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_art_diving_delete_project_delete_projectad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naive_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('about_title', models.TextField(verbose_name='О проекте(заголовок)')),
                ('about_1', models.TextField(verbose_name='О проекте(абз. 1)')),
                ('about_2', models.TextField(verbose_name='О проекте(абз. 2)')),
                ('about_3', models.TextField(verbose_name='О проекте(абз. 3)')),
                ('details_title', models.TextField(verbose_name='Детали(заголовок)')),
                ('details_1', models.TextField(verbose_name='Детали(абз. 1)')),
                ('details_2', models.TextField(verbose_name='Детали(абз. 2)')),
                ('details_3', models.TextField(verbose_name='Детали(абз. 3)')),
            ],
            options={
                'verbose_name': 'Наивные вопросы',
                'verbose_name_plural': 'Наивные вопросы',
            },
        ),
        migrations.AlterModelOptions(
            name='art_diving',
            options={'verbose_name': 'Арт-дивинг', 'verbose_name_plural': 'Арт-дивинг'},
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b1',
            field=models.TextField(default=1, verbose_name='О проекте(бл. 1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b1_en',
            field=models.TextField(null=True, verbose_name='О проекте(бл. 1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b1_ru',
            field=models.TextField(null=True, verbose_name='О проекте(бл. 1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b2',
            field=models.TextField(default=1, verbose_name='О проекте(бл. 2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b2_en',
            field=models.TextField(null=True, verbose_name='О проекте(бл. 2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b2_ru',
            field=models.TextField(null=True, verbose_name='О проекте(бл. 2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b3',
            field=models.TextField(default=2, verbose_name='О проекте(бл. 3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b3_en',
            field=models.TextField(null=True, verbose_name='О проекте(бл. 3)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='about_b3_ru',
            field=models.TextField(null=True, verbose_name='О проекте(бл. 3)'),
        ),
    ]
