# Generated by Django 5.0.4 on 2024-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_naive_questions_alter_art_diving_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_diving',
            name='details_b1',
            field=models.TextField(default=1, verbose_name='Детали(бл. 1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='details_b2',
            field=models.TextField(default=1, verbose_name='Детали(бл. 2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='details_b3',
            field=models.TextField(default=1, verbose_name='Детали(бл. 3)'),
            preserve_default=False,
        ),
    ]
