# Generated by Django 5.0.4 on 2024-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_art_diving_details_b1_art_diving_details_b2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_diving',
            name='details_b1_en',
            field=models.TextField(null=True, verbose_name='Детали(бл. 1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='details_b1_ru',
            field=models.TextField(null=True, verbose_name='Детали(бл. 1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='details_b2_en',
            field=models.TextField(null=True, verbose_name='Детали(бл. 2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='details_b2_ru',
            field=models.TextField(null=True, verbose_name='Детали(бл. 2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='details_b3_en',
            field=models.TextField(null=True, verbose_name='Детали(бл. 3)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='details_b3_ru',
            field=models.TextField(null=True, verbose_name='Детали(бл. 3)'),
        ),
    ]
