# Generated by Django 5.0.4 on 2024-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_art_diving_details_b1_en_art_diving_details_b1_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_diving',
            name='we_can',
            field=models.TextField(default=1, verbose_name='Умеем'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_1',
            field=models.TextField(default=1, verbose_name='Умеем_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_1_en',
            field=models.TextField(null=True, verbose_name='Умеем_1'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_1_ru',
            field=models.TextField(null=True, verbose_name='Умеем_1'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_2',
            field=models.TextField(default=1, verbose_name='Умеем_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_2_en',
            field=models.TextField(null=True, verbose_name='Умеем_2'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_2_ru',
            field=models.TextField(null=True, verbose_name='Умеем_2'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_3',
            field=models.TextField(default=1, verbose_name='Умеем_3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_3_en',
            field=models.TextField(null=True, verbose_name='Умеем_3'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_3_ru',
            field=models.TextField(null=True, verbose_name='Умеем_3'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_4',
            field=models.TextField(default=1, verbose_name='Умеем_4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_4_en',
            field=models.TextField(null=True, verbose_name='Умеем_4'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_4_ru',
            field=models.TextField(null=True, verbose_name='Умеем_4'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_en',
            field=models.TextField(null=True, verbose_name='Умеем'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_ru',
            field=models.TextField(null=True, verbose_name='Умеем'),
        ),
    ]
