# Generated by Django 5.0.4 on 2024-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_art_diving_we_can_art_diving_we_can_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_diving',
            name='we_can_1_title',
            field=models.TextField(default=1, verbose_name='Умеем_1(заг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_1_title_en',
            field=models.TextField(null=True, verbose_name='Умеем_1(заг.)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_1_title_ru',
            field=models.TextField(null=True, verbose_name='Умеем_1(заг.)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_2_title',
            field=models.TextField(default=1, verbose_name='Умеем_2(заг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_2_title_en',
            field=models.TextField(null=True, verbose_name='Умеем_2(заг.)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_2_title_ru',
            field=models.TextField(null=True, verbose_name='Умеем_2(заг.)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_3_title',
            field=models.TextField(default=1, verbose_name='Умеем_3(заг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_3_title_en',
            field=models.TextField(null=True, verbose_name='Умеем_3(заг.)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_3_title_ru',
            field=models.TextField(null=True, verbose_name='Умеем_3(заг.)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_4_title',
            field=models.TextField(default=1, verbose_name='Умеем_4(заг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_4_title_en',
            field=models.TextField(null=True, verbose_name='Умеем_4(заг.)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='we_can_4_title_ru',
            field=models.TextField(null=True, verbose_name='Умеем_4(заг.)'),
        ),
    ]
