# Generated by Django 5.0.4 on 2024-05-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0014_art_diving_we_can_1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_1',
            field=models.TextField(default=1, verbose_name='Реализация(инф.1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_1_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_1_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_2',
            field=models.TextField(default=1, verbose_name='Реализация(инф.2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_2_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_2_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_3',
            field=models.TextField(default=1, verbose_name='Реализация(инф.3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_3_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.3)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_3_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.3)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_4',
            field=models.TextField(default=1, verbose_name='Реализация(инф.4)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_4_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.4)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_4_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.4)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_5',
            field=models.TextField(default=1, verbose_name='Реализация(инф.5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_5_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.5)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_ext_5_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.5)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_header',
            field=models.TextField(default=1, verbose_name='Реализация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_header_en',
            field=models.TextField(null=True, verbose_name='Реализация'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_header_ru',
            field=models.TextField(null=True, verbose_name='Реализация'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_1',
            field=models.TextField(default=1, verbose_name='Реализация(заг.1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_1_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_1_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.1)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_2',
            field=models.TextField(default=1, verbose_name='Реализация(заг.2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_2_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_2_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.2)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_3',
            field=models.TextField(default=1, verbose_name='Реализация(заг.3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_3_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.3)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_3_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.3)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_4',
            field=models.TextField(default=1, verbose_name='Реализация(заг.4)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_4_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.4)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_4_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.4)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_5',
            field=models.TextField(default=1, verbose_name='Реализация(заг.5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_5_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.5)'),
        ),
        migrations.AddField(
            model_name='art_diving',
            name='impl_title_5_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.5)'),
        ),
    ]
