# Generated by Django 5.0.4 on 2024-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0015_art_diving_impl_ext_1_art_diving_impl_ext_1_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naive_questions',
            name='about_3',
        ),
        migrations.RemoveField(
            model_name='naive_questions',
            name='details_2',
        ),
        migrations.RemoveField(
            model_name='naive_questions',
            name='details_3',
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='about_1_en',
            field=models.TextField(null=True, verbose_name='О проекте(абз. 1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='about_1_ru',
            field=models.TextField(null=True, verbose_name='О проекте(абз. 1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='about_2_en',
            field=models.TextField(null=True, verbose_name='О проекте(абз. 2)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='about_2_ru',
            field=models.TextField(null=True, verbose_name='О проекте(абз. 2)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='about_title_en',
            field=models.TextField(null=True, verbose_name='О проекте(заголовок)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='about_title_ru',
            field=models.TextField(null=True, verbose_name='О проекте(заголовок)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='details_1_en',
            field=models.TextField(null=True, verbose_name='Детали(абз. 1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='details_1_ru',
            field=models.TextField(null=True, verbose_name='Детали(абз. 1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='details_title_en',
            field=models.TextField(null=True, verbose_name='Детали(заголовок)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='details_title_ru',
            field=models.TextField(null=True, verbose_name='Детали(заголовок)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_1',
            field=models.TextField(default=1, verbose_name='Реализация(инф.1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_1_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_1_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_2',
            field=models.TextField(default=1, verbose_name='Реализация(инф.2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_2_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.2)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_2_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.2)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_3',
            field=models.TextField(default=1, verbose_name='Реализация(инф.3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_3_en',
            field=models.TextField(null=True, verbose_name='Реализация(инф.3)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_ext_3_ru',
            field=models.TextField(null=True, verbose_name='Реализация(инф.3)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_header',
            field=models.TextField(default=1, verbose_name='Реализация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_header_en',
            field=models.TextField(null=True, verbose_name='Реализация'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_header_ru',
            field=models.TextField(null=True, verbose_name='Реализация'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_1',
            field=models.TextField(default=1, verbose_name='Реализация(заг.1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_1_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_1_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.1)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_2',
            field=models.TextField(default=1, verbose_name='Реализация(заг.2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_2_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.2)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_2_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.2)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_3',
            field=models.TextField(default=1, verbose_name='Реализация(заг.3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_3_en',
            field=models.TextField(null=True, verbose_name='Реализация(заг.3)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='impl_title_3_ru',
            field=models.TextField(null=True, verbose_name='Реализация(заг.3)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can',
            field=models.TextField(default=1, verbose_name='Умеем'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_1',
            field=models.TextField(default=1, verbose_name='Умеем_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_1_en',
            field=models.TextField(null=True, verbose_name='Умеем_1'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_1_ru',
            field=models.TextField(null=True, verbose_name='Умеем_1'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_1_title',
            field=models.TextField(default=1, verbose_name='Умеем_1(заг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_1_title_en',
            field=models.TextField(null=True, verbose_name='Умеем_1(заг.)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_1_title_ru',
            field=models.TextField(null=True, verbose_name='Умеем_1(заг.)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_2',
            field=models.TextField(default=1, verbose_name='Умеем_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_2_en',
            field=models.TextField(null=True, verbose_name='Умеем_2'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_2_ru',
            field=models.TextField(null=True, verbose_name='Умеем_2'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_2_title',
            field=models.TextField(default=1, verbose_name='Умеем_2(заг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_2_title_en',
            field=models.TextField(null=True, verbose_name='Умеем_2(заг.)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_2_title_ru',
            field=models.TextField(null=True, verbose_name='Умеем_2(заг.)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_3',
            field=models.TextField(default=1, verbose_name='Умеем_3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_3_en',
            field=models.TextField(null=True, verbose_name='Умеем_3'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_3_ru',
            field=models.TextField(null=True, verbose_name='Умеем_3'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_3_title',
            field=models.TextField(default=1, verbose_name='Умеем_3(заг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_3_title_en',
            field=models.TextField(null=True, verbose_name='Умеем_3(заг.)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_3_title_ru',
            field=models.TextField(null=True, verbose_name='Умеем_3(заг.)'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_en',
            field=models.TextField(null=True, verbose_name='Умеем'),
        ),
        migrations.AddField(
            model_name='naive_questions',
            name='we_can_ru',
            field=models.TextField(null=True, verbose_name='Умеем'),
        ),
    ]
