# Generated by Django 5.0.4 on 2024-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0016_remove_naive_questions_about_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_cartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('about_title', models.TextField(verbose_name='О проекте(заголовок)')),
                ('about_title_ru', models.TextField(null=True, verbose_name='О проекте(заголовок)')),
                ('about_title_en', models.TextField(null=True, verbose_name='О проекте(заголовок)')),
                ('about_1', models.TextField(verbose_name='О проекте(абз. 1)')),
                ('about_1_ru', models.TextField(null=True, verbose_name='О проекте(абз. 1)')),
                ('about_1_en', models.TextField(null=True, verbose_name='О проекте(абз. 1)')),
                ('about_2', models.TextField(verbose_name='О проекте(абз. 2)')),
                ('about_2_ru', models.TextField(null=True, verbose_name='О проекте(абз. 2)')),
                ('about_2_en', models.TextField(null=True, verbose_name='О проекте(абз. 2)')),
                ('details_title', models.TextField(verbose_name='Детали(заголовок)')),
                ('details_title_ru', models.TextField(null=True, verbose_name='Детали(заголовок)')),
                ('details_title_en', models.TextField(null=True, verbose_name='Детали(заголовок)')),
                ('details_1', models.TextField(verbose_name='Детали(абз. 1)')),
                ('details_1_ru', models.TextField(null=True, verbose_name='Детали(абз. 1)')),
                ('details_1_en', models.TextField(null=True, verbose_name='Детали(абз. 1)')),
                ('details_2', models.TextField(verbose_name='Детали(абз. 2)')),
                ('details_2_ru', models.TextField(null=True, verbose_name='Детали(абз. 2)')),
                ('details_2_en', models.TextField(null=True, verbose_name='Детали(абз. 2)')),
                ('details_3', models.TextField(verbose_name='Детали(абз. 3)')),
                ('details_3_ru', models.TextField(null=True, verbose_name='Детали(абз. 3)')),
                ('details_3_en', models.TextField(null=True, verbose_name='Детали(абз. 3)')),
                ('details_4', models.TextField(verbose_name='Детали(абз. 4)')),
                ('details_4_ru', models.TextField(null=True, verbose_name='Детали(абз. 4)')),
                ('details_4_en', models.TextField(null=True, verbose_name='Детали(абз. 4)')),
                ('impl_header', models.TextField(verbose_name='Реализация')),
                ('impl_header_ru', models.TextField(null=True, verbose_name='Реализация')),
                ('impl_header_en', models.TextField(null=True, verbose_name='Реализация')),
                ('impl_title', models.TextField(verbose_name='Объявление')),
                ('impl_title_ru', models.TextField(null=True, verbose_name='Объявление')),
                ('impl_title_en', models.TextField(null=True, verbose_name='Объявление')),
                ('impl_1', models.TextField(verbose_name='Реализация(бл.1)')),
                ('impl_1_ru', models.TextField(null=True, verbose_name='Реализация(бл.1)')),
                ('impl_1_en', models.TextField(null=True, verbose_name='Реализация(бл.1)')),
                ('impl_2', models.TextField(verbose_name='Реализация(бл.2)')),
                ('impl_2_ru', models.TextField(null=True, verbose_name='Реализация(бл.2)')),
                ('impl_2_en', models.TextField(null=True, verbose_name='Реализация(бл.2)')),
                ('impl_3', models.TextField(verbose_name='Реализация(бл.3)')),
                ('impl_3_ru', models.TextField(null=True, verbose_name='Реализация(бл.3)')),
                ('impl_3_en', models.TextField(null=True, verbose_name='Реализация(бл.3)')),
            ],
            options={
                'verbose_name': 'Арт-картель',
                'verbose_name_plural': 'Арт-картель',
            },
        ),
    ]
