# Generated by Django 5.0.4 on 2024-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_art_cartel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_cartel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='art_cartel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='art_cartel',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='art_cartel',
            name='description_1',
            field=models.TextField(default=1, verbose_name='Описание1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_cartel',
            name='description_1_en',
            field=models.TextField(null=True, verbose_name='Описание1'),
        ),
        migrations.AddField(
            model_name='art_cartel',
            name='description_1_ru',
            field=models.TextField(null=True, verbose_name='Описание1'),
        ),
        migrations.AddField(
            model_name='art_cartel',
            name='description_2',
            field=models.TextField(default=1, verbose_name='Описание2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_cartel',
            name='description_2_en',
            field=models.TextField(null=True, verbose_name='Описание2'),
        ),
        migrations.AddField(
            model_name='art_cartel',
            name='description_2_ru',
            field=models.TextField(null=True, verbose_name='Описание2'),
        ),
    ]
