# Generated by Django 5.0.4 on 2024-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Члены команды'},
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='team', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=1000, verbose_name='Роль в команде'),
        ),
    ]
