# Generated by Django 5.0.4 on 2024-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='team',
            name='role_en',
            field=models.TextField(null=True, verbose_name='Роль в команде'),
        ),
        migrations.AddField(
            model_name='team',
            name='role_ru',
            field=models.TextField(null=True, verbose_name='Роль в команде'),
        ),
    ]
